### ISSUE TITLE
安装故障 - 呼吸灯补丁安装会报错

### ISSUE THREAD

**Issue by Pengree** [wzpan/wukong-contrib#28]
在"麦克风选购建议"这篇文档中：
https://wukong.hahack.com/#/mic-choices?id=respeaker-2-mics-pi-hat
提到了“呼吸灯补丁”：
![image](https://user-images.githubusercontent.com/14105110/53331683-75d8d680-392c-11e9-97c7-7cbde1f14850.png)

测试了一下，这个程序安装会报错：
pi@Rasperry:~/wukong-robot $ git cherry-pick c12ca91
error: 不能应用 c12ca91... feat(respeaker): 接入 respeaker 的 pixels 驱动
提示：冲突解决完毕后，用 'git add <路径>' 或 'git rm <路径>'
提示：对修正后的文件做标记，然后用 'git commit' 提交

它在wukong.py里添加了如下几行：
pi@Rsapberry:~/wukong-robot $ more wukong.py
……

    def _detected_callback(self):
        if not utils.is_proper_time():
            logger.warning('勿扰模式开启中')
            return
<<<<<<< HEAD
        if self._conversation.isRecording:
            logger.warning('正在录音中，跳过')
            return
=======
        pixels.wakeup()
>>>>>>> c12ca91... feat(respeaker): 接入 respeaker 的 pixels 驱动
        Player.play(constants.getData('beep_hi.wav'))
        logger.info('开始录音')
        self._conversation.interrupt()
        self._conversation.isRecording = True;

……

我的环境是：
硬件：Respberry 3b+
软件版本：
pi@Rsapberry:~ $ uname -a
Linux Rsapberry 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
手动安装方式。

**Comment by wzpan** [comment]
@Pengree 使用问题请提到 [wukong-robot 的 issue 页](https://github.com/wzpan/wukong-robot/issues) 。这里只处理跟插件相关的问题。
