### ISSUE TITLE
关于插件LocalPlayer插件代码

### ISSUE THREAD

**Issue by cgn5566** [wzpan/wukong-contrib#35]
亲爱的大神@wzpan你好，最近学习开发robot的技能，遇到点问题想请教下您，是这样的，我是在插件代码里面调用UNIT 的，在插件代码里面定义了SERVICE_ID、API_KEY、SECRET_KEY，然后通过from robot.sdk import unit使用unit.getUnit、unit.getSlots这些函数。
您说 ”虽然插件中调 UNIT 可以让插件正常工作，但你不该在最终的代码中这么做“，我的理解使用UNIT 必须要先提供SERVICE_ID、API_KEY、SECRET_KEY这些参数的，如果在插件代码中删除了，后台的配置文件里面也没有提供SERVICE_ID、API_KEY、SECRET_KEY这些值，那么wukong又怎么获取到这些参数呢？
比如LocalPayer这个插件，里面没有任何有关定义SERVICE_ID、API_KEY、SECRET_KEY的代码，但是却能使用self.nlu.hasIntent(parsed, 'MUSICRANK')去判断意图，悟空是怎么知道UNIT的SERVICE_ID、API_KEY、SECRET_KEY的啊？
wukong的插件技能很灵活也很实用，我非常喜欢，希望大神@wzpan能指点一下，我会努力开发出更多好玩实用的技能。

**Comment by wzpan** [comment]
wukong-robot 本身是有一个 UNIT 的账户的。当最终发布的时候，需要你提供这个 UNIT 技能的分享码，审核通过后，我将集成进这个 UNIT 账户里头。统一有这个账户来解析。

**Comment by cgn5566** [comment]
亲爱的大神@wzpan您好！感谢您的解答，您说wukong-robot 本身是有一个 UNIT 的账户，请问这个UNIT账户的SERVICE_ID、API_KEY、SECRET_KEY这些参数是wukong-robot文件夹下面定义的吗，奇怪的是我仔细看了NLU.py、unit.py、constants.py、Conversation.py、Brain.py、wukong.py等py文件中都没有找到您所说的UNIT 账户。能分享一下UNIT 的账户信息所在文件的位置吗？十分感谢！

**Comment by wzpan** [comment]
在 Brain.py ：https://github.com/wzpan/wukong-robot/blob/master/robot/Brain.py#L38

**Comment by cgn5566** [comment]
谢谢!
大神@wzpan德艺双馨！O(∩_∩)O
