### ISSUE TITLE
插件的后台运行

### ISSUE THREAD

**Issue by xunqing** [wzpan/wukong-contrib#36]
大神 @wzpan 你好，我这边用wukong做了一个智能家居的软件，想要监控各个设备的状态，目前打算是每10s轮询一次，离线及在线使用语音播报，但wukong的插件好像是关键字调用，调用结束后会退出，一直在后台功能该如何实现呢？请大神指点个思路 蟹蟹。

**Comment by wzpan** [comment]
这种就可以开发一个沉浸式插件

**Comment by xunqing** [comment]
好的。抱歉浪费你时间了。非常感谢
