### ISSUE TITLE
有关悟空录音的采样率

### ISSUE THREAD

**Issue by cgn5566** [wzpan/wukong-contrib#68]
大神您好！最近悟空在重启的时候会报错：Invalid sample rate -9997，导致悟空无法正常唤醒，奇怪的是这种情况是随机出现的。网上说是由于设备的采样率设置的不对导致的，我主机是树莓派，用的是usb的麦克风，我看了usb设备的采样率是[44100, 48000, 96000]这三个，请问悟空使用的采样率是多少啊？是不是我设备的可用采样率和悟空的不一致啊？我可以修改悟空的采样率吗？应该到哪个文件里面改呢？无法唤醒这个问题出现的还挺频繁的，也很严重，这段时间被这个问题搞的快头疼死了，麻烦大神百忙之中指点一下如何修改悟空的采样率吧，十分感谢！！！

**Comment by wzpan** [comment]
关于wukong-robot本身的问题而非插件的问题，请移步到 [wukong-robot 的 issues 页](https://github.com/wzpan/wukong-robot/issues?utf8=%E2%9C%93&q=Invalid+sample+rate+-9997) 提交。

**Comment by cgn5566** [comment]
已经解决了  谢谢！
