### ISSUE TITLE
Hass插件在2.4G Wifi下执行过慢

### ISSUE THREAD

**Issue by sirarikako** [wzpan/wukong-contrib#81]
ha和wukong在同一个路由下。
安装wukong的树莓派用有线连接路由的话，用后台文本命令，大概3-5秒左右就可以看到设备有反应。
但是在和路由器比较远的地方，大概需要10秒才可以。

大致看了下，貌似是每次执行都要获取group和automation以外所有实体的属性。感觉在wifi下因为无线延迟的问题，导致取得实体属性时间过长。

虽然说插网线速度就可以接受，不过wukong作为智能音箱来使用的话，肯定是在屋子里任意地方放置。所以希望可以改善下处理。

比如，在wukong这边可以指定控制设备的一览来降低取得实体属性的次数，或者提前缓存实体属性并增加刷新设备的命令来在HA修改后刷新实体属性的缓存。

谢谢。

**Comment by wzpan** [comment]
> 比如，在wukong这边可以指定控制设备的一览来降低取得实体属性的次数，或者提前缓存实体属性并增加刷新设备的命令来在HA修改后刷新实体属性的缓存。

听起来合理。我支持下。

**Comment by wzpan** [comment]
![image](https://user-images.githubusercontent.com/1631405/84596228-0a06de00-ae8f-11ea-95ef-eae52a463fe1.png)

@sirarikako 插件 1.6.3 版本已发布。支持了设备信息的缓存，并且可以通过“刷新设备缓存”指令来强制刷新一下设备缓存。

**Comment by sirarikako** [comment]
@wzpan 谢谢
